
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA IF NOT EXISTS flix;

CREATE TABLE IF NOT EXISTS flix.comments
(
    id_comment bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    id_post bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    parent_comment_id bigint,
    gif_url character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT comments_pkey PRIMARY KEY (id_comment)
);

CREATE TABLE IF NOT EXISTS flix.movie_review_likes
(
    id_like serial NOT NULL,
    id_review integer NOT NULL,
    id_user bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movie_review_likes_pkey PRIMARY KEY (id_like),
    CONSTRAINT uq_movie_review_likes UNIQUE (id_review, id_user)
);

CREATE TABLE IF NOT EXISTS flix.movie_reviews
(
    id_review serial NOT NULL,
    tmdb_movie_id integer NOT NULL,
    id_user bigint NOT NULL,
    parent_review_id integer,
    content text COLLATE pg_catalog."default" NOT NULL,
    rating smallint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT movie_reviews_pkey PRIMARY KEY (id_review)
);

CREATE TABLE IF NOT EXISTS flix.password_reset_tokens
(
    id_reset serial NOT NULL,
    id_user bigint NOT NULL,
    token_hash text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    used_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id_reset)
);

CREATE TABLE IF NOT EXISTS flix.post_likes
(
    id_like bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    id_post bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_likes_pkey PRIMARY KEY (id_like),
    CONSTRAINT uq_post_like UNIQUE (id_user, id_post)
);

CREATE TABLE IF NOT EXISTS flix.post_poll_options
(
    id_option bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_poll bigint NOT NULL,
    option_text character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT post_poll_options_pkey PRIMARY KEY (id_option)
);

CREATE TABLE IF NOT EXISTS flix.post_poll_votes
(
    id_vote bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_poll bigint NOT NULL,
    id_option bigint NOT NULL,
    id_user bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_poll_votes_pkey PRIMARY KEY (id_vote),
    CONSTRAINT uq_post_poll_user UNIQUE (id_poll, id_user)
);

CREATE TABLE IF NOT EXISTS flix.post_polls
(
    id_poll bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_post bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_polls_pkey PRIMARY KEY (id_poll),
    CONSTRAINT post_polls_id_post_key UNIQUE (id_post)
);

CREATE TABLE IF NOT EXISTS flix.post_reactions
(
    id_reaction bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    id_post bigint NOT NULL,
    reaction_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_reactions_pkey PRIMARY KEY (id_reaction),
    CONSTRAINT uq_post_reaction UNIQUE (id_user, id_post)
);

CREATE TABLE IF NOT EXISTS flix.post_shares
(
    id_share bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_post bigint NOT NULL,
    id_user bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_shares_pkey PRIMARY KEY (id_share)
);

CREATE TABLE IF NOT EXISTS flix.post_views
(
    id_view bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_post bigint NOT NULL,
    id_user bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_views_pkey PRIMARY KEY (id_view)
);

CREATE TABLE IF NOT EXISTS flix.posts
(
    id_post bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_user bigint NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    image_url character varying(255) COLLATE pg_catalog."default",
    title character varying(300) COLLATE pg_catalog."default",
    tags text[] COLLATE pg_catalog."default" DEFAULT '{}'::text[],
    post_type character varying(20) COLLATE pg_catalog."default" DEFAULT 'post'::character varying,
    CONSTRAINT posts_pkey PRIMARY KEY (id_post)
);

CREATE TABLE IF NOT EXISTS flix.roles
(
    id_role bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id_role),
    CONSTRAINT roles_role_name_key UNIQUE (role_name)
);

INSERT INTO flix.roles (role_name, description)
VALUES
    ('registered_user', 'User biasa yang sudah terdaftar'),
    ('moderator', 'Moderator komunitas'),
    ('admin', 'Administrator aplikasi')
ON CONFLICT (role_name) DO UPDATE
    SET description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS flix.tv_series_review_likes
(
    id_like serial NOT NULL,
    id_review integer NOT NULL,
    id_user bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tv_series_review_likes_pkey PRIMARY KEY (id_like),
    CONSTRAINT uq_tv_series_review_likes UNIQUE (id_review, id_user)
);

CREATE TABLE IF NOT EXISTS flix.tv_series_reviews
(
    id_review serial NOT NULL,
    tmdb_series_id integer NOT NULL,
    id_user bigint NOT NULL,
    parent_review_id integer,
    content text COLLATE pg_catalog."default" NOT NULL,
    rating smallint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tv_series_reviews_pkey PRIMARY KEY (id_review)
);

CREATE TABLE IF NOT EXISTS flix.users
(
    id_user bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_role bigint NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    profile_photo_url text COLLATE pg_catalog."default",
    banner_url text COLLATE pg_catalog."default",
    profile_photo_position character varying(30) COLLATE pg_catalog."default" DEFAULT '50% 50%'::character varying,
    banner_position character varying(30) COLLATE pg_catalog."default" DEFAULT '50% 50%'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id_user),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT fk_comments_parent FOREIGN KEY (parent_comment_id)
    REFERENCES flix.comments (id_comment) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT fk_comments_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.comments
    ADD CONSTRAINT fk_comments_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.movie_review_likes
    ADD CONSTRAINT movie_review_likes_id_review_fkey FOREIGN KEY (id_review)
    REFERENCES flix.movie_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_movie_review_likes_id_review
    ON flix.movie_review_likes(id_review);


ALTER TABLE IF EXISTS flix.movie_review_likes
    ADD CONSTRAINT movie_review_likes_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.movie_reviews
    ADD CONSTRAINT movie_reviews_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.movie_reviews
    ADD CONSTRAINT movie_reviews_parent_review_id_fkey FOREIGN KEY (parent_review_id)
    REFERENCES flix.movie_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_movie_reviews_parent_review_id
    ON flix.movie_reviews(parent_review_id);


ALTER TABLE IF EXISTS flix.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_id_user
    ON flix.password_reset_tokens(id_user);


ALTER TABLE IF EXISTS flix.post_likes
    ADD CONSTRAINT fk_post_likes_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_likes
    ADD CONSTRAINT fk_post_likes_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_options
    ADD CONSTRAINT fk_post_poll_options_poll FOREIGN KEY (id_poll)
    REFERENCES flix.post_polls (id_poll) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_votes
    ADD CONSTRAINT fk_post_poll_votes_option FOREIGN KEY (id_option)
    REFERENCES flix.post_poll_options (id_option) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_votes
    ADD CONSTRAINT fk_post_poll_votes_poll FOREIGN KEY (id_poll)
    REFERENCES flix.post_polls (id_poll) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_poll_votes
    ADD CONSTRAINT fk_post_poll_votes_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_polls
    ADD CONSTRAINT fk_post_polls_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS post_polls_id_post_key
    ON flix.post_polls(id_post);


ALTER TABLE IF EXISTS flix.post_reactions
    ADD CONSTRAINT fk_post_reactions_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_reactions
    ADD CONSTRAINT fk_post_reactions_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_shares
    ADD CONSTRAINT fk_post_shares_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.post_shares
    ADD CONSTRAINT fk_post_shares_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS flix.post_views
    ADD CONSTRAINT fk_post_views_post FOREIGN KEY (id_post)
    REFERENCES flix.posts (id_post) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_post_views_id_post
    ON flix.post_views(id_post);


ALTER TABLE IF EXISTS flix.post_views
    ADD CONSTRAINT fk_post_views_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_post_views_id_user
    ON flix.post_views(id_user);


ALTER TABLE IF EXISTS flix.posts
    ADD CONSTRAINT fk_posts_user FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.tv_series_review_likes
    ADD CONSTRAINT tv_series_review_likes_id_review_fkey FOREIGN KEY (id_review)
    REFERENCES flix.tv_series_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tv_series_review_likes_id_review
    ON flix.tv_series_review_likes(id_review);


ALTER TABLE IF EXISTS flix.tv_series_review_likes
    ADD CONSTRAINT tv_series_review_likes_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.tv_series_reviews
    ADD CONSTRAINT tv_series_reviews_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS flix.tv_series_reviews
    ADD CONSTRAINT tv_series_reviews_parent_review_id_fkey FOREIGN KEY (parent_review_id)
    REFERENCES flix.tv_series_reviews (id_review) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_tv_series_reviews_parent_review_id
    ON flix.tv_series_reviews(parent_review_id);


ALTER TABLE IF EXISTS flix.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (id_role)
    REFERENCES flix.roles (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS flix.watchlist
(
    id_watchlist serial NOT NULL,
    id_user bigint NOT NULL,
    media_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tmdb_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    poster_url text COLLATE pg_catalog."default",
    backdrop_url text COLLATE pg_catalog."default",
    release_date character varying(30) COLLATE pg_catalog."default",
    overview text COLLATE pg_catalog."default",
    vote_average numeric(4,2),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT watchlist_pkey PRIMARY KEY (id_watchlist),
    CONSTRAINT uq_watchlist_user_media UNIQUE (id_user, media_type, tmdb_id),
    CONSTRAINT chk_watchlist_media_type CHECK (media_type::text = ANY (ARRAY['movie'::character varying, 'tv'::character varying]::text[])),
    CONSTRAINT chk_watchlist_status CHECK (status::text = ANY (ARRAY['pending'::character varying, 'watched'::character varying]::text[]))
);

ALTER TABLE IF EXISTS flix.watchlist
    ADD CONSTRAINT watchlist_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES flix.users (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_watchlist_user_status
    ON flix.watchlist(id_user, status);

CREATE INDEX IF NOT EXISTS idx_watchlist_user_media
    ON flix.watchlist(id_user, media_type, tmdb_id);

END;
